# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 1.17
      uses: actions/setup-java@v3
      with:
        java-version: 1.17
        distribution: 'temurin'
        server-id: ossrh
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
        settings-path: ${{ github.workspace }}

    - name: Build with Maven
      run: mvn -Prelease-sign-artifacts -B verify --file pom.xml

    - name: Publish to GitHub Packages Apache Maven
      run: mvn --batch-mode deploy
      env:
        MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
